name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Export environment variables
        env:
            STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
            TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
        run: |
            echo "STRIPE_API_KEY=${STRIPE_API_KEY}" >> .env
            echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> .env    
            echo "TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}" >> .env

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
